version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo pip install -r requirements.txt

      - run:
          name: run test
          command: |
            ls
            pytest --cov-report term-missing --cov=lazy
            codecov --token=3f44ac03-59d3-42e1-965f-fd47b2f1a7ab
            codecov
